In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [5]:
df.isnull().sum()
#There is no null values

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [7]:
X = df.drop('label',axis=1)
Y=df['label']
X_test= test

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
print(X_scaled)
print(X.shape)
print(Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(42000, 784)
0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64


In [20]:
X_train,X_valid,y_train,y_valid = train_test_split(X_scaled,Y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(33600, 784)
(8400, 784)
(33600,)
(8400,)


In [77]:
#Building model 
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.activations import relu,linear
from tensorflow.keras.optimizers import Adam
model = keras.Sequential([
    layers.Dense(units=784,activation='relu'),
    layers.Dense(units=512,activation='relu'),
    layers.Dense(units=10,activation='linear')
])
model.compile(loss = SparseCategoricalCrossentropy(from_logits=True),optimizer=Adam(learning_rate=0.01),metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8016 - loss: 1.1962
Epoch 2/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8076 - loss: 0.7634
Epoch 3/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6599 - loss: 1.1515
Epoch 4/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6381 - loss: 1.1847
Epoch 5/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5741 - loss: 1.3277
Epoch 6/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5036 - loss: 1.3861
Epoch 7/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.4755 - loss: 1.4332
Epoch 8/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.4812 - loss: 1.4144
Epoch 9/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.4964 - loss: 1.4298
Epoch 10/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.4876 - loss: 1.4414
Epoch 11/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.4986 - loss: 1.4017
Epoch 12/100
1050/1

In [78]:
model.summary()

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_51 (Dense)                     │ (32, 784)                   │         615,440 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_52 (Dense)                     │ (32, 512)                   │         401,920 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_53 (Dense)                     │ (32, 10)                    │           5,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,067,472 (11.70 MB)

 Trainable params: 1,022,490 (3.90 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,044,982 (7.80 MB)

In [79]:
eva_first_model = model.evaluate(X_train,y_train)
print(f"Evaluation of first model on training set: {eva_first_model}")

1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.5224 - loss: 1.2324
Evaluation of first model on training set: [1.258314609527588, 0.5221726298332214]


In [80]:
eva_first_model_cv = model.evaluate(X_valid,y_valid)
print(f"Evaluation of first model on cross-validation set: {eva_first_model_cv}")

263/263 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - accuracy: 0.5039 - loss: 3.7773
Evaluation of first model on cross-validation set: [2.7659502029418945, 0.5071428418159485]


In [82]:
second_model = keras.Sequential([
    layers.Dense(units=30,activation='relu'),
    layers.Dense(units=30,activation='relu'),
    layers.Dense(units=10,activation='linear')
])
second_model.compile(loss = SparseCategoricalCrossentropy(from_logits=True),optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
second_model.fit(X_train,y_train,epochs=100)

Epoch 1/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 513us/step - accuracy: 0.7936 - loss: 0.6950
Epoch 2/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step - accuracy: 0.9452 - loss: 0.1775
Epoch 3/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 514us/step - accuracy: 0.9618 - loss: 0.1261
Epoch 4/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 511us/step - accuracy: 0.9704 - loss: 0.0955
Epoch 5/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 511us/step - accuracy: 0.9756 - loss: 0.0779
Epoch 6/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step - accuracy: 0.9798 - loss: 0.0668
Epoch 7/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 510us/step - accuracy: 0.9830 - loss: 0.0529
Epoch 8/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 510us/step - accuracy: 0.9854 - loss: 0.0457
Epoch 9/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 510us/step - accuracy: 0.9860 - loss: 0.0406
Epoch 10/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 525us/step - accuracy: 0.9887 - loss: 0.0347
Epoch 11/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 504us/step - accuracy: 0.9895 - loss: 0.03

In [83]:
second_model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_54 (Dense)                     │ (32, 30)                    │          23,550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_55 (Dense)                     │ (32, 30)                    │             930 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_56 (Dense)                     │ (32, 10)                    │             310 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 74,372 (290.52 KB)

 Trainable params: 24,790 (96.84 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 49,582 (193.68 KB)

In [84]:
eva_second_model = second_model.evaluate(X_train,y_train)
print(f"Evaluation of fsecond model on training set: {eva_second_model}")
eva_second_model_cv = second_model.evaluate(X_valid,y_valid)
print(f"Evaluation of second model on cross-validation set: {eva_second_model_cv}")

1050/1050 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.9972 - loss: 0.0123
Evaluation of fsecond model on training set: [0.01188859436661005, 0.9971428513526917]
263/263 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9509 - loss: 0.7803
Evaluation of second model on cross-validation set: [0.7151100039482117, 0.9535714387893677]


In [86]:
third_model = keras.Sequential([
    layers.Dense(units=5,activation='relu'),
    layers.Dense(units=15,activation='relu'),
    layers.Dense(units=15,activation='relu'),
    layers.Dense(units=10,activation='linear')
])
third_model.compile(loss = SparseCategoricalCrossentropy(from_logits=True),optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
third_model.fit(X_train,y_train,epochs=100)

Epoch 1/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 507us/step - accuracy: 0.5663 - loss: 1.2748
Epoch 2/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step - accuracy: 0.8540 - loss: 0.5162
Epoch 3/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 494us/step - accuracy: 0.8748 - loss: 0.4330
Epoch 4/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 495us/step - accuracy: 0.8844 - loss: 0.4115
Epoch 5/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 491us/step - accuracy: 0.8922 - loss: 0.3843
Epoch 6/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 495us/step - accuracy: 0.8947 - loss: 0.3672
Epoch 7/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 504us/step - accuracy: 0.8979 - loss: 0.3561
Epoch 8/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 514us/step - accuracy: 0.8992 - loss: 0.3500
Epoch 9/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 500us/step - accuracy: 0.8983 - loss: 0.3435
Epoch 10/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 501us/step - accuracy: 0.8996 - loss: 0.3438
Epoch 11/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 501us/step - accuracy: 0.9027 - loss: 0.33

In [87]:
eva_third_model = third_model.evaluate(X_train,y_train)
print(f"Evaluation of third model on training set: {eva_third_model}")
eva_third_model_cv = third_model.evaluate(X_valid,y_valid)
print(f"Evaluation of third model on cross-validation set: {eva_third_model_cv}")

1050/1050 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.9254 - loss: 0.2415
Evaluation of third model on training set: [0.24145019054412842, 0.9256547689437866]
263/263 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8967 - loss: 0.3969
Evaluation of third model on cross-validation set: [0.40532463788986206, 0.8941666483879089]


In [88]:
fourth_model = keras.Sequential([
    layers.Dense(units=10,activation='relu'),
    layers.Dense(units=10,activation='relu'),
    layers.Dense(units=10,activation='linear')
])
fourth_model.compile(loss = SparseCategoricalCrossentropy(from_logits=True),optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
fourth_model.fit(X_train,y_train,epochs=100)

Epoch 1/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 471us/step - accuracy: 0.6062 - loss: 1.1939
Epoch 2/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 473us/step - accuracy: 0.9012 - loss: 0.3435
Epoch 3/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 472us/step - accuracy: 0.9204 - loss: 0.2664
Epoch 4/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 481us/step - accuracy: 0.9332 - loss: 0.2283
Epoch 5/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 475us/step - accuracy: 0.9348 - loss: 0.2169
Epoch 6/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 473us/step - accuracy: 0.9374 - loss: 0.2038
Epoch 7/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 472us/step - accuracy: 0.9366 - loss: 0.2034
Epoch 8/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 482us/step - accuracy: 0.9432 - loss: 0.1891
Epoch 9/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 473us/step - accuracy: 0.9456 - loss: 0.1814
Epoch 10/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 484us/step - accuracy: 0.9463 - loss: 0.1828
Epoch 11/100
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 475us/step - accuracy: 0.9470 - loss: 0.17

In [89]:
eva_fourth_model = fourth_model.evaluate(X_train,y_train)
print(f"Evaluation of third model on training set: {eva_fourth_model}")
eva_fourth_model_cv = fourth_model.evaluate(X_valid,y_valid)
print(f"Evaluation of third model on cross-validation set: {eva_fourth_model_cv}")


1050/1050 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.9727 - loss: 0.0839
Evaluation of third model on training set: [0.08511192351579666, 0.9723511934280396]
263/263 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9154 - loss: 0.6389
Evaluation of third model on cross-validation set: [0.7228097915649414, 0.9116666913032532]
